apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: portfolio
spec:
  selector:
    app: react-app 
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000 
    targetPort: 3000 